### ISSUE TITLE
【 JSON API 】data-jsonをjsで変更した際に描画されない

### ISSUE THREAD

**Issue by Watayo** [qniapp/qni#199]
【やりたいこと】
・<quantum-circuit>タグのdata-json 属性を JS から動的に変更したときに描画する。
【できていないこと】
・https://yasuhito.github.io/qni/json_api.html　を参考にHTMLに直書きしたが、エラーは出ないものの描画されない。

**Comment by yasuhito** [comment]
@Watayo #198 で修正してみましたので、確認してもらえますか?
