### ISSUE TITLE
CDNで呼び出したが、JSON-APIが動作しない

### ISSUE THREAD

**Issue by Watayo** [qniapp/qni#200]
【現状】
・CDN読み込み　`<script src="https://unpkg.com/browse/@qni/elements@0.0.44/"></script>`
・HTMLに直で`<quantum-circuit id="quantum-circuit"></quantum-circuit>`
・APIにPOST →`document.getElementById("quantum-circuit").setAttribute("data-json", '{"cols":[["|0>","|0>"],["H",1],["•","X"],["Measure",1],[1,"Measure"]]}')});`
をしたが、描画されない。

**Comment by yasuhito** [comment]
CDN のリンクは https://unpkg.com/@qni/elements@0.0.44/dist/index.js を使ってみてください。
`unpkg.com/browse/...` はブラウザで開く用のパスです。

**Comment by yasuhito** [comment]
@Watayo  たとえば次のような html を試してみてください。
注意点として `@qni/elements` を使うときは .js のほかに .css のロードが必要です。

```html
<!doctype html>
<html>
  <head>
    <title>load @qni/elements</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://unpkg.com/@qni/elements@0.0.45/dist/qni.css" rel="stylesheet" />
    <script type="module" src="https://unpkg.com/@qni/elements@0.0.45/dist/index.js" defer></script>
  </head>
  <body>
    <quantum-circuit id="quantum-circuit"></quantum-circuit>

    <script>
     document.getElementById("quantum-circuit")
             .setAttribute("data-json", '{"cols":[["|0>","|0>"],["H",1],["•","X"],["Measure",1],[1,"Measure"]]}');
    </script>
  </body>
</html>
```

**Comment by yasuhito** [comment]
@Watayo このイシューは閉じても大丈夫でしょうか? (動いているっぽいのを湊さんのツイートで見ました 笑)
