### ISSUE TITLE
Firefoxでゲートをドラッグで消せない

### ISSUE THREAD

**Issue by nakatamaho** [qniapp/qni#201]
Firefoxで任意のゲート(たとえばHゲート)を置きます。そのままドラッグしてブラウザの外に出します。これでこのゲートは消えるはずですが、消えません。

git でのバージョンは、
commit 756b2a7525faf8ac9545d205324ee8d08ffd5cc8 (HEAD -> main, origin/main, origin/HEAD)
Author: Yasuhito Takamiya <yasuhito@hey.com>
Date:   Thu Apr 7 14:43:57 2022 +0900

    add data-hoverable tests (#196)
です。

**Comment by yasuhito** [comment]
@nakatamaho OS は Windows であっているでしょうか? Mac の Firefox で確認してみましたが、そちらではゲートを消すことができました。

**Comment by nakatamaho** [comment]
yes, Windowsです。

ただし、
https://qniapp.net/
で、Win/macOS両方で、firefoxを使って試したところ問題なく消せました。

**Comment by yasuhito** [comment]
確認ありがとうございます! ではちょっと前のバージョンでのバグだと思うので、いったんイシューは閉じます。
また問題起こったら reopen してください。
