### ISSUE TITLE
setAttributeにて描画が更新されず追加された状態になる。

### ISSUE THREAD

**Issue by Watayo** [qniapp/qni#206]
行った動作　一度setAttributeにて回路を描画した後に新たにsetAttributeでdata-jsonを更新する。
想定　あらたな回路が正しく描画される。
実際　前の回路の続きに新たな回路が追加される。

わかっていること
data-jsonは更新されている。circuit-stepが更新されていない。

**Comment by Watayo** [comment]
let json_circ = JSON.stringify(circ_matrix);
let circuit_node = document.getElementById("quantum-circuit");
circuit_node.innerHTML="";
circuit_node.setAttribute("data-json", `{"cols":${json_circ}}`);

**Comment by yasuhito** [comment]
@Watayo 修正して 0.0.46 をリリースしました。
