### ISSUE TITLE
回路上のコメントについて

### ISSUE THREAD

**Issue by satsubatsutaro** [qniapp/qni#253]
webアプリ画面から回路にコメント(下の画像の「量子もつれ」のようなコメント)を入れる方法はありますでしょうか。
![image](https://user-images.githubusercontent.com/812333/179399840-7ba01340-0414-4ff7-bbcb-2c390cbcfe95.png)

**Comment by yasuhito** [comment]
残念ながら Web アプリ上からブロックを入れる機能はまだ実装できていません。
なにか単純な UI が思い付けばなのですが、なかなかいい方法がみつからず後回しになっています。

たとえばコメントブロックを 2 つ連続して作った場合、ブロック間に空白として何もしないステップを 1 つ自動的に入れるとか、ブロック内のゲートをすべて消した場合ブロックも自動的に消すとか、そのあたりの処理がちょっとめんどくさそうだなと思っています。

**Comment by satsubatsutaro** [comment]
ご返信ありがとうございます。
承知しました、クローズで大丈夫です！
