### ISSUE TITLE
Remove *.lock file

### ISSUE THREAD

**Issue by nakatamaho** [qniapp/qni#81]
You can remove the following files since they have been generated after building qni.

* trunk
./packages/elements/yarn.lock
./packages/simulator/yarn.lock
./yarn.lock
./apps/www/Gemfile.lock
./apps/www/docs/Gemfile.lock
./docs/Gemfile.lock

* cirq-backend
./apps/www/docs/Gemfile.lock
./apps/www/Gemfile.lock
./packages/elements/yarn.lock
./packages/simulator/yarn.lock
./yarn.lock
./docs/Gemfile.lock

Thanks!

**Comment by yasuhito** [comment]
The yarn and bundle lock files are not generated after the build but are used to install the package before the build. Therefore the lock files are in the git repository. See https://classic.yarnpkg.com/en/docs/yarn-lock/ for more information.

**Comment by nakatamaho** [comment]
i see, then I close this issue. thanks for your comment.
